### PR TITLE
Fix absolute position of mobile menu & add background to menu

### PR DESCRIPTION
**Pull request by maksrojek**
https://tree.taiga.io/project/fierycod-knit-front-vuejs/task/133

### CODE REVIEW

**Comment by FieryCod** [comment]
Hi @maksrojek!

Welcome in the team and congratulations to you for your first PR on this project.
You are now the member of the KNIT development team. You are a developer so you got all permissions as we have.
But with great power comes great responsibility.

One more time great job, thanks for PR and welcome on board mate.

**Comment by FieryCod** [comment]
Package-lock was added on my demand. I experienced problems while trying to install modules on a new copy of a repo.

**Comment by k911** [comment]
Good job!

**Comment by gitsobek** [comment]
Looks good to me.

**Pull request merged**
