### PR TITLE
docs(contributing): Create contributing guide

### PR DESCRIPTION
**Pull request by k911**
Should include following topics:
- [x] Making first contribution :heavy_check_mark:
- [x]  Rebasing branch with develop :heavy_check_mark:
- [x] Commitizen usage :heavy_check_mark:
- [x] Conventions :heavy_check_mark:
- [x] PR Policy (Squash or Rebase) :heavy_check_mark:

If you'd like to help @knit-pk/web please add commits directly to this branch we'll squash them

### CODE REVIEW

**Comment by FieryCod** [comment]
@k911 Seems legit for me. May I merge this? Good job!!!

**Comment by k911** [comment]
I'd like to add this ones in this PR too:

- Rebasing branch with develop
- Commitizen usage
- Conventions (generally add links to docs/)
- PR Policy (Squash or Rebase)

**Comment by FieryCod** [comment]
Ok, so we will patiently wait for it! 👍

**Comment by k911** [comment]
I think it is ready now.

**Comment by FieryCod** [comment]
Good job @k911! 👍 🎉 🎉

**Pull request merged**
