### PR TITLE
Add fully workable category widget

### PR DESCRIPTION
**Pull request by FieryCod**
## This PR realizes the task:
https://tree.taiga.io/project/fierycod-knit-front-vuejs/task/168

## Commits includes following changes:
- **Add categories widget in articles list page** 
_basic layout + some polishes_
- **Fix logic of changing the categoryCode**
_Because of the fact that the categoryCode was changed to early wrong articles collection was passed to the ArticleCardList component which caused the blank page. This commit fixes this wrong behaviour._

### CODE REVIEW

**Comment by k911** [comment]
Everything great but, I really do not like idea of introducing new top level directories. Could it be `store-settings/categories.js` -> `store/settings/categories.js` please?

**Comment by FieryCod** [comment]
@k911 I strongly sympathize with your feeling. I do not like it either but it's necessary. 

## Here is why:
We know that `nuxt.js` watches some of the directories for example `layouts`, `pages` and `store`.

**Because of that it provides us with some nice features like:** 
- analyzing the source code
- creating the modules from those source files

**What does it mean for us?**
It means that whenever we add something to `store` directory then some new store module will be created. This impacts the store modules:
- adds more hooks, watchers to properties and so on
- vuex tab in developers tools are full of unnecessary information about settings

Because of all those things we decided with @zrebcu411 that the `store-settings` although painful is necessary.

**Comment by FieryCod** [comment]
@k911 we got config folder maybe I will move those settings to `config/store`?

**Comment by k911** [comment]
Yes, that's better :) Could you please, also rebase to get rid of this merges? 😄

**Comment by FieryCod** [comment]
@k911 Please approve :D I gonna squash the commits :)

**Pull request merged**
