### PR TITLE
Add styles for page transition

### PR DESCRIPTION
**Pull request by AndrzejSala**

### CODE REVIEW

**Comment by FieryCod** [comment]
I think that we should decrease time to 0.2 or 0.3 @zrebcu411 what do you think?

**Comment by k911** [comment]
Nice thing, but would make it custom named transition (not default which is 'page'), and add to nuxt.config.js transition export, to be able to switch to other one when needed, keeping this one too, because enabling it for every route could be annoying.

https://nuxtjs.org/api/configuration-transition#the-transition-property

**Comment by AndrzejSala** [comment]
@FieryCod  0.3s looks really nice.

@k911 I wonder if it makes sense to put extra entry to config for such a trifle without any real problem.
It seems to me that for the final users of this project, page transition is cool or crap thing.

I just think that adding extra config when it is really needed works really fine.

**Comment by k911** [comment]
@AndrzejSala no problem, that's only suggestion, but again, I think that enabling these transition for every route would be really annoying, especially on mobile devices.. Thus I predict, that this additional config will be added really soon anyway.

**Comment by AndrzejSala** [comment]
@zrebcu411 
Thanks for comment. According to your suggestion I changed transition time to 0.2 and remove transform property.

**Pull request merged**
