### PR TITLE
Hide unused components

### PR DESCRIPTION
**Pull request by gitsobek**

### CODE REVIEW

**Comment by k911** [comment]
Could you please remove this:

screen shot 2018-03-13 at 18 22 14

too?

**Comment by k911** [comment]
`job-offers-widget` should be disabled too according to the current `NODE_ENV` environment variable. (if `NODE_ENV` = `production`, then disable job offers widget)

**Comment by FieryCod** [comment]
As far as i know we should hide all widgets.

**Comment by maksrojek** [comment]
What about "projects-widget", it should be hidden too.

**Pull request merged**
