### PR TITLE
Feature/rwd improvements

### PR DESCRIPTION
**Pull request by zrebcu411**

### CODE REVIEW

**Comment by FieryCod** [comment]
Could you please delete the merge commit?

**Comment by FieryCod** [comment]
Leftside-wrapper should have max-width set too 100%

**Comment by zrebcu411** [comment]
Why the leftside wrapper should have max-width: 100%? Yup, i have to squash the commits. But we did not do it before when merging develop to feature branch before PR.

**Comment by FieryCod** [comment]
@zrebcu411 check iphone 4 resolution. leftiside wrapper is to wide and it destroys the layout.

**Comment by zrebcu411** [comment]
No, the only problem is callendar and projects widgets, which have fixed temporary widths. When we’ll hide it, problem will be solved.

**Comment by FieryCod** [comment]
ok

**Pull request merged**
